@base = http://localhost:3000
# @base = https://mobster-backend-production.up.railway.app
@mobId = 9c98238b-a576-4354-9a71-9e341ba9717b
@memberId = 596a9d1e-b3a2-4b2e-8ace-ada6063bcb50

### Create new mob - name
POST {{base}}/mobs
Content-Type: application/json

{
  "mobName": "JAR"
}

### Get all mobs
GET {{base}}/mobs

### Get a mob by mobid
GET {{base}}/mobs/{{mobId}}

### Add mob member
POST {{base}}/mobs/{{mobId}}/members
Content-Type: application/json

{
  "name": "Allan",
  "height": 180
}

### Get mob members by mobid
GET {{base}}/mobs/{{mobId}}/members

### Get mob member by mobid and memberid
GET {{base}}/mobs/{{mobId}}/members/{{memberId}}

### Get mob member by mobid and memberid
GET {{base}}/mobs/{{mobId}}/members/blabla

### Send generally incorrect
GET {{base}}/nonsense

### Send generally incorrect
GET {{base}}/mobs/you

