@base = http://localhost:3000
@mobId = a9531436-bfcc-46bd-95b7-fad631f987a2
@memberId = c5f119f1-cf54-46f5-afb6-89a1eaa19af6

### Create new mob - name
POST {{base}}/mobs
Content-Type: application/json

{
  "mobName": ""
}

### Get all mobs
GET {{base}}/mobs

### Get a mob by mobid
GET {{base}}/mobs/{{mobId}}

### Add mob member
POST {{base}}/mobs/{{mobId}}/members
Content-Type: application/json

{
  "name": "Person zero",
  "height": 123
}

### Get mob members by mobid
GET {{base}}/mobs/{{mobId}}/members

### Get mob member by mobid and memberid
GET {{base}}/mobs/{{mobId}}/members/{{memberId}}

### Get mob member by mobid and memberid
GET {{base}}/mobs/{{mobId}}/members/blabla

### Send generally incorrect
GET {{base}}/nonsense

### Send generally incorrect
GET {{base}}/mobs/you

